"""
Normalized data transfer objects for cross-provider communication.
"""

from .base import BaseDTO, BulkResult, ConnectionTestResult, PaginatedResult, ProviderMeta
from .email import EmailAddress, EmailAttachmentContent, EmailAttachmentInfo, EmailDetail, EmailSummary
from .feed import FeedResult, FeedUploadResult, FeedValidationError, FeedValidationResult, FeedWarning
from .llm import (
    ChatMessage,
    ChatRole,
    EmbeddingResult,
    FinishReason,
    ImageResult,
    LLMChunk,
    LLMResponse,
    ModelInfo,
    ModelPricing,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    TranscriptionResult,
)
from .message import (
    DeliveryReport,
    DeliveryStatus,
    InboundMessage,
    MessageAttachment,
    MessageChannel,
    MessageContact,
    MessageLocation,
    OutboundMessage,
)
from .order import Order, OrderItem, OrderStatus, PaymentStatus, PaymentType
from .partner import Address, Contact
from .payment import BillingDetails, CheckoutSession, PaymentMethodType, PaymentResult, Refund
from .product import (
    AttributeDefinition,
    AttributeValue,
    Product,
    ProductAttribute,
    ProductCategory,
    ProductPhoto,
    ProductUpdate,
    ProductVariant,
    RelatedProductLink,
)
from .saved_payment import CardBrand, SavedPaymentMethod
from .shipment import AWBLabel, Parcel, Shipment, ShipmentStatus, TrackingEvent
from .subscription import Subscription, SubscriptionInterval, SubscriptionStatus
from .webhook import WebhookEvent, WebhookEventType

__all__ = [
    "AWBLabel",
    "Address",
    "AttributeDefinition",
    "AttributeValue",
    "BaseDTO",
    "BillingDetails",
    "BulkResult",
    "CardBrand",
    "ChatMessage",
    "ChatRole",
    "CheckoutSession",
    "ConnectionTestResult",
    "Contact",
    "DeliveryReport",
    "DeliveryStatus",
    "EmailAddress",
    "EmailAttachmentContent",
    "EmailAttachmentInfo",
    "EmailDetail",
    "EmailSummary",
    "EmbeddingResult",
    "FeedResult",
    "FeedUploadResult",
    "FeedValidationError",
    "FeedValidationResult",
    "FeedWarning",
    "FinishReason",
    "ImageResult",
    "InboundMessage",
    "LLMChunk",
    "LLMResponse",
    "MessageAttachment",
    "MessageChannel",
    "MessageContact",
    "MessageLocation",
    "ModelInfo",
    "ModelPricing",
    "Order",
    "OrderItem",
    "OrderStatus",
    "OutboundMessage",
    "PaginatedResult",
    "Parcel",
    "PaymentMethodType",
    "PaymentResult",
    "PaymentStatus",
    "PaymentType",
    "Product",
    "ProductAttribute",
    "ProductCategory",
    "ProductPhoto",
    "ProductUpdate",
    "ProductVariant",
    "ProviderMeta",
    "Refund",
    "RelatedProductLink",
    "SavedPaymentMethod",
    "Shipment",
    "ShipmentStatus",
    "Subscription",
    "SubscriptionInterval",
    "SubscriptionStatus",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "TrackingEvent",
    "TranscriptionResult",
    "WebhookEvent",
    "WebhookEventType",
]
