"""
Normalized data transfer objects for cross-provider communication.
"""

from .ads import (
    Ad,
    AdCampaign,
    AdCreative,
    AdEntityStatus,
    AdGroup,
    AdInsights,
    AdInsightsLevel,
    AdMediaAsset,
    AdMediaType,
    AdObjective,
    AdTargeting,
    UploadedAdMedia,
)
from .base import (
    BaseDTO,
    BulkItemResult,
    BulkResult,
    BulkUpsertResult,
    ConnectionTestResult,
    PaginatedResult,
    ProviderMeta,
)
from .dns import DnsRecord, DnsZone, DnsZoneSnapshot
from .email import (
    EmailAddress,
    EmailAttachmentContent,
    EmailAttachmentInfo,
    EmailDetail,
    EmailSummary,
    InboxAction,
    InboxActionType,
)
from .feed import FeedResult, FeedUploadResult, FeedValidationError, FeedValidationResult, FeedWarning
from .financial import FinancialInvoice, FinancialInvoiceLine, FinancialTransaction, FinancialTransactionType
from .hosting import HostingAccount, HostingDomain, HostingResource, Mailbox, PanelLink
from .llm import (
    ChatMessage,
    ChatRole,
    EmbeddingResult,
    FinishReason,
    ImageResult,
    LLMChunk,
    LLMResponse,
    ModelInfo,
    ModelPricing,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    TranscriptionResult,
)
from .message import (
    DeliveryReport,
    DeliveryStatus,
    InboundMessage,
    MessageAttachment,
    MessageChannel,
    MessageContact,
    MessageLocation,
    OutboundMessage,
)
from .network import DetectedDnsAllowlist, DnsAllowlist, NetworkClient, NetworkDeviceInfo, NetworkSegment
from .order import Order, OrderItem, OrderStatus, PaymentStatus, PaymentType
from .partner import Address, Contact
from .payment import BillingDetails, CheckoutSession, PaymentMethodType, PaymentResult, Refund
from .product import (
    AttributeDefinition,
    AttributeValue,
    Product,
    ProductAttribute,
    ProductCategory,
    ProductPhoto,
    ProductUpdate,
    ProductVariant,
    RelatedProductLink,
)
from .returns import ReturnKind, ShopReturn, ShopReturnLine, ShopReturnRefund
from .saved_payment import CardBrand, SavedPaymentMethod
from .shipment import AWBLabel, Parcel, Shipment, ShipmentStatus, TrackingEvent
from .shop_rules import CustomerPricing, CustomerProductPercent, OrderValueTier, ShopRules
from .social import (
    PublishResult,
    PublishStatus,
    SocialAccount,
    SocialAccountStats,
    SocialMediaType,
    SocialPost,
    SocialPostDraft,
    SocialPostStats,
    SocialPrivacy,
)
from .subscription import Subscription, SubscriptionInterval, SubscriptionStatus
from .webhook import WebhookEvent, WebhookEventType

__all__ = [
    "AWBLabel",
    "Ad",
    "AdCampaign",
    "AdCreative",
    "AdEntityStatus",
    "AdGroup",
    "AdInsights",
    "AdInsightsLevel",
    "AdMediaAsset",
    "AdMediaType",
    "AdObjective",
    "AdTargeting",
    "Address",
    "AttributeDefinition",
    "AttributeValue",
    "BaseDTO",
    "BillingDetails",
    "BulkItemResult",
    "BulkResult",
    "BulkUpsertResult",
    "CardBrand",
    "ChatMessage",
    "ChatRole",
    "CheckoutSession",
    "ConnectionTestResult",
    "Contact",
    "CustomerPricing",
    "CustomerProductPercent",
    "DeliveryReport",
    "DeliveryStatus",
    "DetectedDnsAllowlist",
    "DnsAllowlist",
    "DnsRecord",
    "DnsZone",
    "DnsZoneSnapshot",
    "EmailAddress",
    "EmailAttachmentContent",
    "EmailAttachmentInfo",
    "EmailDetail",
    "EmailSummary",
    "EmbeddingResult",
    "FeedResult",
    "FeedUploadResult",
    "FeedValidationError",
    "FeedValidationResult",
    "FeedWarning",
    "FinancialInvoice",
    "FinancialInvoiceLine",
    "FinancialTransaction",
    "FinancialTransactionType",
    "FinishReason",
    "HostingAccount",
    "HostingDomain",
    "HostingResource",
    "ImageResult",
    "InboundMessage",
    "InboxAction",
    "InboxActionType",
    "LLMChunk",
    "LLMResponse",
    "Mailbox",
    "MessageAttachment",
    "MessageChannel",
    "MessageContact",
    "MessageLocation",
    "ModelInfo",
    "ModelPricing",
    "NetworkClient",
    "NetworkDeviceInfo",
    "NetworkSegment",
    "Order",
    "OrderItem",
    "OrderStatus",
    "OrderValueTier",
    "OutboundMessage",
    "PaginatedResult",
    "PanelLink",
    "Parcel",
    "PaymentMethodType",
    "PaymentResult",
    "PaymentStatus",
    "PaymentType",
    "Product",
    "ProductAttribute",
    "ProductCategory",
    "ProductPhoto",
    "ProductUpdate",
    "ProductVariant",
    "ProviderMeta",
    "PublishResult",
    "PublishStatus",
    "Refund",
    "RelatedProductLink",
    "ReturnKind",
    "SavedPaymentMethod",
    "Shipment",
    "ShipmentStatus",
    "ShopReturn",
    "ShopReturnLine",
    "ShopReturnRefund",
    "ShopRules",
    "SocialAccount",
    "SocialAccountStats",
    "SocialMediaType",
    "SocialPost",
    "SocialPostDraft",
    "SocialPostStats",
    "SocialPrivacy",
    "Subscription",
    "SubscriptionInterval",
    "SubscriptionStatus",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "TrackingEvent",
    "TranscriptionResult",
    "UploadedAdMedia",
    "WebhookEvent",
    "WebhookEventType",
]
